export const CALL_API_LOG_IN_ACTION = 'CALL_API_LOG_IN_ACTION';
export const CALL_API_SIGN_UP_ACTION = 'CALL_API_SIGN_UP_ACTION';
export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDDEN_LOADING = 'HIDDEN_LOADING';
